# Generated by Django 5.2.4 on 2025-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', 'add_new_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='name',
            field=models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek')], max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='PersonalPrompt',
        ),
    ]
