# Generated by Django 5.2.4 on 2025-07-11 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('groq', 'Groq'), ('github', 'GitHub Copilot'), ('cohere', 'Cohere'), ('mistral', 'Mistral AI')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_info', models.JSONField(blank=True, default=dict)),
                ('total_tokens', models.IntegerField(default=0, help_text='کل توکن\u200cهای موجود')),
                ('used_tokens', models.IntegerField(default=0, help_text='توکن\u200cهای مصرف شده')),
                ('rate_limit', models.CharField(blank=True, help_text='محدودیت نرخ', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_manager.aiprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='PersonalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('odoo', 'Odoo Development'), ('wordpress', 'WordPress'), ('django', 'Django'), ('debug', 'Debug & Fix')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='ai_manager.apikey')),
            ],
            options={
                'verbose_name': 'Personal Prompt',
                'verbose_name_plural': 'Personal Prompts',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='ai_manager.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
