# Generated by Django 5.2.4 on 2025-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0001_alter_aiprovider_name_delete_personalprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['name'], 'verbose_name': 'AI Provider', 'verbose_name_plural': 'AI Providers'},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Token Usage', 'verbose_name_plural': 'Token Usage'},
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='model_info',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='total_tokens',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='used_tokens',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='آیا اتصال تست شده'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='model_name',
            field=models.CharField(blank=True, help_text='مدل انتخاب شده', max_length=100),
        ),
    ]
