# Generated by Django 5.2.4 on 2025-07-11 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['name'], 'verbose_name': 'AI Provider', 'verbose_name_plural': 'AI Providers'},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='آیا اتصال تست شده'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='model_name',
            field=models.CharField(blank=True, help_text='مدل انتخاب شده', max_length=100),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='ai_manager.apikey')),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage',
                'ordering': ['-timestamp'],
            },
        ),
    ]
