# Generated by Django 5.2.4 on 2025-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0002_alter_aiprovider_options_alter_apikey_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='apikey',
            name='model_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit',
            field=models.CharField(blank=True, help_text='محدودیت نرخ', max_length=100),
        ),
        migrations.AddField(
            model_name='apikey',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='کل توکن\u200cهای موجود'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='used_tokens',
            field=models.IntegerField(default=0, help_text='توکن\u200cهای مصرف شده'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
