# Generated by Django 5.2.4 on 2025-07-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_manager', '0003_alter_aiprovider_options_alter_apikey_options_and_more'),
        ('ai_manager', 'add_new_providers'),
    ]

    operations = [
    ]
