# Generated by Django 5.2.4 on 2025-07-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Profile Name')),
                ('technologies', models.CharField(blank=True, max_length=255, verbose_name='Selected Technologies')),
                ('custom_prompt', models.TextField(blank=True, help_text='Add any other specific instructions or project context here.', verbose_name='Your Custom Instructions')),
                ('system_prompt', models.TextField(blank=True, editable=False, help_text='This is auto-generated based on your selections.', verbose_name='Generated System Prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('template_text', models.TextField(help_text='Use {{user_message}} as a placeholder.', verbose_name='Template Content')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
