# Generated by Django 5.0.1 on 2025-07-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.RemoveField(
            model_name='githubtoken',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='updated_at',
        ),
    ]
